#!/usr/bin/env python3
"""Generate build.ninja for the glint project."""

from __future__ import annotations

from pathlib import Path


# =============================================================================
# Configuration
# =============================================================================

PROJECT = "glint"
BUILD_DIR = "build"

APP_SRCS = [
    "src/main.c",
    "src/gl.c",
    "src/gl_core.c",
    "src/gl_bindings.c",
]

TEST_SRCS = [
    "tests/test_gl_core.c",
    "tests/test_gl_bindings.c",
    "src/gl_core.c",
    "src/gl_bindings.c",
]

TEST_LIBS = [
    "pocketpy",
]

VENDOR_LIBS = [
    {
        "name": "glfw",
        "srcs": [
            "vendor/glfw/src/context.c",
            "vendor/glfw/src/init.c",
            "vendor/glfw/src/input.c",
            "vendor/glfw/src/monitor.c",
            "vendor/glfw/src/platform.c",
            "vendor/glfw/src/vulkan.c",
            "vendor/glfw/src/window.c",
            "vendor/glfw/src/egl_context.c",
            "vendor/glfw/src/glx_context.c",
            "vendor/glfw/src/osmesa_context.c",
            "vendor/glfw/src/null_init.c",
            "vendor/glfw/src/null_joystick.c",
            "vendor/glfw/src/null_monitor.c",
            "vendor/glfw/src/null_window.c",
            "vendor/glfw/src/linux_joystick.c",
            "vendor/glfw/src/posix_module.c",
            "vendor/glfw/src/posix_poll.c",
            "vendor/glfw/src/posix_thread.c",
            "vendor/glfw/src/posix_time.c",
            "vendor/glfw/src/x11_init.c",
            "vendor/glfw/src/x11_monitor.c",
            "vendor/glfw/src/x11_window.c",
            "vendor/glfw/src/xkb_unicode.c",
        ],
        "incs": [
            "vendor/glfw/include",
            "vendor/glfw/src",
        ],
        "defs": [
            "_GLFW_X11",
            "_DEFAULT_SOURCE",
        ],
    },
    {
        "name": "pocketpy",
        "srcs": [
            "vendor/pocketpy/pocketpy.c",
        ],
        "incs": [
            "vendor/pocketpy",
        ],
        "defs": [],
        "cflags": "--std=c11 -ffunction-sections -fdata-sections",
    },
    {
        "name": "miniaudio",
        "srcs": [
            "vendor/miniaudio/miniaudio.c",
        ],
        "incs": [
            "vendor/miniaudio",
        ],
        "defs": [],
    },
]

EXTRA_INCS = [
    "src",
    "vendor/glad/include",
]


# =============================================================================
# Helpers
# =============================================================================

def escape(value: str) -> str:
    return value.replace("$", "$$").replace(" ", "$")


def join(values: list[str]) -> str:
    return " ".join(escape(v) for v in values)


def obj_path(config: str, src: str) -> str:
    return f"{BUILD_DIR}/{config}/obj/{src[:-2]}.o"


def named_obj_path(config: str, group: str, src: str) -> str:
    return f"{BUILD_DIR}/{config}/obj/{group}/{src[:-2]}.o"


def archive_path(config: str, name: str) -> str:
    return f"{BUILD_DIR}/{config}/lib{name}.a"


def target_path(config: str) -> str:
    suffix = "" if config == "release" else "-debug"
    return f"{BUILD_DIR}/{PROJECT}{suffix}"


def test_target_path(config: str) -> str:
    suffix = "" if config == "release" else "-debug"
    return f"{BUILD_DIR}/{PROJECT}-tests{suffix}"


# =============================================================================
# Generator
# =============================================================================

def build_ninja_text() -> str:
    # Collect all includes and defines
    all_incs = EXTRA_INCS[:]
    all_defs = []
    for lib in VENDOR_LIBS:
        all_incs.extend(lib.get("incs", []))
        all_defs.extend(lib.get("defs", []))

    # Unique-ify while preserving order
    seen = set()
    unique_incs = []
    for inc in all_incs:
        if inc not in seen:
            seen.add(inc)
            unique_incs.append(inc)

    seen = set()
    unique_defs = []
    for def_ in all_defs:
        if def_ not in seen:
            seen.add(def_)
            unique_defs.append(def_)

    cppflags = " ".join(f"-I{inc}" for inc in unique_incs)
    cppflags += " " + " ".join(f"-D{def_}" for def_ in unique_defs)

    common_cflags = "-std=c11 -ffunction-sections -fdata-sections"
    app_warnings = "-Wall -Wextra -Wpedantic -Werror"
    vendor_warnings = "-w"
    release_cflags = "-Os -DNDEBUG"
    debug_cflags = "-O0 -g3"
    release_ldflags = "-Wl,--gc-sections -Wl,-s"
    debug_ldflags = ""
    ldlibs = "-lm -ldl -lpthread"

    lines = [
        "# ============================================================================",
        "# Auto-generated by tools/gen_build_ninja.py",
        "# Do not edit manually -- run `python3 tools/gen_build_ninja.py` instead",
        "# ============================================================================",
        "",
        "ninja_required_version = 1.7",
        "cc = cc",
        "ar = ar",
        "",
        f"cppflags = {cppflags}",
        f"common_cflags = {common_cflags}",
        f"app_warnings = {app_warnings}",
        f"vendor_warnings = {vendor_warnings}",
        f"release_cflags = {release_cflags}",
        f"debug_cflags = {debug_cflags}",
        f"release_ldflags = {release_ldflags}",
        f"debug_ldflags = {debug_ldflags}",
        f"ldlibs = {ldlibs}",
        "",
        "rule cc",
        '  command = mkdir -p $$(dirname "$out") && $cc $cppflags $cflags $mode_cflags $warnings -MMD -MF $out.d -c $in -o $out',
        "  depfile = $out.d",
        "  deps = gcc",
        "  description = CC $out",
        "",
        "rule ar",
        '  command = mkdir -p $$(dirname "$out") && rm -f $out && $ar rcs $out $in',
        "  description = AR $out",
        "",
        "rule link",
        '  command = mkdir -p $$(dirname "$out") && $cc $ldflags $in -o $out $ldlibs',
        "  description = LINK $out",
        "",
        "rule clean",
        "  command = rm -rf build",
        "  description = CLEAN build outputs",
        "",
    ]

    for config, mode_cflags, ldflags in [
        ("release", "$release_cflags", "$release_ldflags"),
        ("debug", "$debug_cflags", "$debug_ldflags"),
    ]:
        lines.append(f"# --- {config} ---")
        archives = []

        # Application objects
        app_objs = [obj_path(config, src) for src in APP_SRCS]
        for src, obj in zip(APP_SRCS, app_objs):
            lines.append(f"build {escape(obj)}: cc {escape(src)}")
            lines.append(f"  cppflags = $cppflags")
            lines.append(f"  cflags = $common_cflags")
            lines.append(f"  mode_cflags = {mode_cflags}")
            lines.append(f"  warnings = $app_warnings")

        # Vendor objects and archives
        for lib in VENDOR_LIBS:
            lib_objs = [obj_path(config, src) for src in lib["srcs"]]
            lib_archive = archive_path(config, lib["name"])

            cflags = lib.get("cflags", "$common_cflags")
            for src, obj in zip(lib["srcs"], lib_objs):
                lines.append(f"build {escape(obj)}: cc {escape(src)}")
                lines.append(f"  cppflags = $cppflags")
                lines.append(f"  cflags = {cflags}")
                lines.append(f"  mode_cflags = {mode_cflags}")
                lines.append(f"  warnings = $vendor_warnings")

            lines.append(f"build {escape(lib_archive)}: ar {join(lib_objs)}")
            archives.append(lib_archive)

        # Link
        target = target_path(config)
        all_inputs = app_objs + archives
        lines.append(f"build {escape(target)}: link {join(all_inputs)}")
        lines.append(f"  ldflags = {ldflags}")
        test_objs = [named_obj_path(config, "tests", src) for src in TEST_SRCS]
        test_archives = [archive_path(config, name) for name in TEST_LIBS]
        for src, obj in zip(TEST_SRCS, test_objs):
            lines.append(f"build {escape(obj)}: cc {escape(src)}")
            lines.append(f"  cppflags = $cppflags")
            lines.append(f"  cflags = $common_cflags")
            lines.append(f"  mode_cflags = {mode_cflags}")
            lines.append(f"  warnings = $app_warnings")
        lines.append(f"build {escape(test_target_path(config))}: link {join(test_objs + test_archives)}")
        lines.append(f"  ldflags = {ldflags}")
        lines.append("")

    # Phony targets
    release_target = escape(target_path("release"))
    debug_target = escape(target_path("debug"))
    release_tests = escape(test_target_path("release"))
    debug_tests = escape(test_target_path("debug"))
    lines.extend([
        f"build {BUILD_DIR}/release: phony {release_target}",
        f"build {BUILD_DIR}/debug: phony {debug_target}",
        f"build release: phony {release_target}",
        f"build debug: phony {debug_target}",
        f"build tests: phony {release_tests}",
        f"build tests-debug: phony {debug_tests}",
        f"build all: phony {release_target} {debug_target} {release_tests} {debug_tests}",
        "build clean: clean",
        f"default {release_target}",
        "",
    ])

    return "\n".join(lines) + "\n"


def main() -> None:
    root = Path(__file__).resolve().parent.parent
    output = root / "build.ninja"
    output.write_text(build_ninja_text(), encoding="ascii")
    print(f"Generated {output}")


if __name__ == "__main__":
    main()
